version: 0.2

env:
  variables:
    PROVIDER_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.10
    commands:
      - CURRENT_BRANCH=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed 's/branch\///g')
      - npm install serverless@3.35.0 -g

  build:
    commands:
      - npm i
      - echo $CURRENT_BRANCH
      #- serverless package --stage $CURRENT_BRANCH
      - serverless package --stage $CURRENT_BRANCH --compile-functions

      - |
        AFFECTED_FUNCTIONS=$(serverless package --stage $CURRENT_BRANCH --compile-functions | grep -oP '(?<=Compiling function: functions/).*?(?=/)')
        echo "Affected functions: $AFFECTED_FUNCTIONS"
        for FUNCTION in $AFFECTED_FUNCTIONS; do
          serverless deploy function --function $FUNCTION --stage $CURRENT_BRANCH
        done






